spring:
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-cliente
            client-secret: palabra-secreta
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:7070/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: apli-cliente
            client-secret: palabra-secreta
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:7070/authorized
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://localhost:9000
             
            
          